general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on && killall qs & q &s  # to avoid having to press a key twice to turn on the display.
}

# === MONITOR DIM (Optimized to fight IPS Glow) ===
listener {
    timeout = 2500                             
    # Drop IPS backlight to absolute minimum and aggressively crush gamma to darken the gray glow
    on-timeout = brightnessctl -s set 1% && hyprctl hyprsunset gamma 15         
    # Restore physical backlight and clear gamma instantly on activity
    on-resume = brightnessctl -r && hyprctl hyprsunset gamma 100                 
}

# === LOCKSCREEN ===
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# === TURN OFF SCREEN ===
listener {
    timeout = 2700                                                
    on-timeout = hyprctl dispatch dpms off                            
    on-resume = hyprctl dispatch dpms on && brightnessctl -r && hyprctl hyprsunset gamma 100          
}

# === SUSPEND ===
listener {
    timeout = 3500
    on-timeout = systemctl suspend        
    on-resume = qs ipc call statusbar reload  
}
